// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.Data;

#nullable disable

namespace TaskManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251205174552_SeedLevels-2")]
    partial class SeedLevels2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TaskManager.Modules.Gamification.Models.Badge", b =>
                {
                    b.Property<int?>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("BadgeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BadgeId");

                    b.ToTable("Badges", (string)null);
                });

            modelBuilder.Entity("TaskManager.Modules.Gamification.Models.Level", b =>
                {
                    b.Property<int?>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("LevelId"));

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaxXp")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("MinXp")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("LevelId");

                    b.ToTable("Levels", (string)null);

                    b.HasData(
                        new
                        {
                            LevelId = 1,
                            LevelName = "Level 1",
                            MaxXp = 99,
                            MinXp = 0
                        },
                        new
                        {
                            LevelId = 2,
                            LevelName = "Level 2",
                            MaxXp = 199,
                            MinXp = 100
                        },
                        new
                        {
                            LevelId = 3,
                            LevelName = "Level 3",
                            MaxXp = 299,
                            MinXp = 200
                        },
                        new
                        {
                            LevelId = 4,
                            LevelName = "Level 4",
                            MaxXp = 399,
                            MinXp = 300
                        },
                        new
                        {
                            LevelId = 5,
                            LevelName = "Level 5",
                            MaxXp = 499,
                            MinXp = 400
                        },
                        new
                        {
                            LevelId = 6,
                            LevelName = "Level 6",
                            MaxXp = 599,
                            MinXp = 500
                        },
                        new
                        {
                            LevelId = 7,
                            LevelName = "Level 7",
                            MaxXp = 699,
                            MinXp = 600
                        },
                        new
                        {
                            LevelId = 8,
                            LevelName = "Level 8",
                            MaxXp = 799,
                            MinXp = 700
                        },
                        new
                        {
                            LevelId = 9,
                            LevelName = "Level 9",
                            MaxXp = 899,
                            MinXp = 800
                        },
                        new
                        {
                            LevelId = 10,
                            LevelName = "Level 10",
                            MaxXp = 999,
                            MinXp = 900
                        },
                        new
                        {
                            LevelId = 11,
                            LevelName = "Level 11",
                            MaxXp = 1099,
                            MinXp = 1000
                        },
                        new
                        {
                            LevelId = 12,
                            LevelName = "Level 12",
                            MaxXp = 1199,
                            MinXp = 1100
                        },
                        new
                        {
                            LevelId = 13,
                            LevelName = "Level 13",
                            MaxXp = 1299,
                            MinXp = 1200
                        },
                        new
                        {
                            LevelId = 14,
                            LevelName = "Level 14",
                            MaxXp = 1399,
                            MinXp = 1300
                        },
                        new
                        {
                            LevelId = 15,
                            LevelName = "Level 15",
                            MaxXp = 1499,
                            MinXp = 1400
                        },
                        new
                        {
                            LevelId = 16,
                            LevelName = "Level 16",
                            MaxXp = 1599,
                            MinXp = 1500
                        },
                        new
                        {
                            LevelId = 17,
                            LevelName = "Level 17",
                            MaxXp = 1699,
                            MinXp = 1600
                        },
                        new
                        {
                            LevelId = 18,
                            LevelName = "Level 18",
                            MaxXp = 1799,
                            MinXp = 1700
                        },
                        new
                        {
                            LevelId = 19,
                            LevelName = "Level 19",
                            MaxXp = 1899,
                            MinXp = 1800
                        },
                        new
                        {
                            LevelId = 20,
                            LevelName = "Level 20",
                            MaxXp = 1999,
                            MinXp = 1900
                        },
                        new
                        {
                            LevelId = 21,
                            LevelName = "Level 21",
                            MaxXp = 2099,
                            MinXp = 2000
                        },
                        new
                        {
                            LevelId = 22,
                            LevelName = "Level 22",
                            MaxXp = 2199,
                            MinXp = 2100
                        },
                        new
                        {
                            LevelId = 23,
                            LevelName = "Level 23",
                            MaxXp = 2299,
                            MinXp = 2200
                        },
                        new
                        {
                            LevelId = 24,
                            LevelName = "Level 24",
                            MaxXp = 2399,
                            MinXp = 2300
                        },
                        new
                        {
                            LevelId = 25,
                            LevelName = "Level 25",
                            MaxXp = 2499,
                            MinXp = 2400
                        },
                        new
                        {
                            LevelId = 26,
                            LevelName = "Level 26",
                            MaxXp = 2599,
                            MinXp = 2500
                        },
                        new
                        {
                            LevelId = 27,
                            LevelName = "Level 27",
                            MaxXp = 2699,
                            MinXp = 2600
                        },
                        new
                        {
                            LevelId = 28,
                            LevelName = "Level 28",
                            MaxXp = 2799,
                            MinXp = 2700
                        },
                        new
                        {
                            LevelId = 29,
                            LevelName = "Level 29",
                            MaxXp = 2899,
                            MinXp = 2800
                        },
                        new
                        {
                            LevelId = 30,
                            LevelName = "Level 30",
                            MaxXp = 2999,
                            MinXp = 2900
                        },
                        new
                        {
                            LevelId = 31,
                            LevelName = "Level 31",
                            MaxXp = 3099,
                            MinXp = 3000
                        },
                        new
                        {
                            LevelId = 32,
                            LevelName = "Level 32",
                            MaxXp = 3199,
                            MinXp = 3100
                        },
                        new
                        {
                            LevelId = 33,
                            LevelName = "Level 33",
                            MaxXp = 3299,
                            MinXp = 3200
                        },
                        new
                        {
                            LevelId = 34,
                            LevelName = "Level 34",
                            MaxXp = 3399,
                            MinXp = 3300
                        },
                        new
                        {
                            LevelId = 35,
                            LevelName = "Level 35",
                            MaxXp = 3499,
                            MinXp = 3400
                        },
                        new
                        {
                            LevelId = 36,
                            LevelName = "Level 36",
                            MaxXp = 3599,
                            MinXp = 3500
                        },
                        new
                        {
                            LevelId = 37,
                            LevelName = "Level 37",
                            MaxXp = 3699,
                            MinXp = 3600
                        },
                        new
                        {
                            LevelId = 38,
                            LevelName = "Level 38",
                            MaxXp = 3799,
                            MinXp = 3700
                        },
                        new
                        {
                            LevelId = 39,
                            LevelName = "Level 39",
                            MaxXp = 3899,
                            MinXp = 3800
                        },
                        new
                        {
                            LevelId = 40,
                            LevelName = "Level 40",
                            MaxXp = 3999,
                            MinXp = 3900
                        },
                        new
                        {
                            LevelId = 41,
                            LevelName = "Level 41",
                            MaxXp = 4099,
                            MinXp = 4000
                        },
                        new
                        {
                            LevelId = 42,
                            LevelName = "Level 42",
                            MaxXp = 4199,
                            MinXp = 4100
                        },
                        new
                        {
                            LevelId = 43,
                            LevelName = "Level 43",
                            MaxXp = 4299,
                            MinXp = 4200
                        },
                        new
                        {
                            LevelId = 44,
                            LevelName = "Level 44",
                            MaxXp = 4399,
                            MinXp = 4300
                        },
                        new
                        {
                            LevelId = 45,
                            LevelName = "Level 45",
                            MaxXp = 4499,
                            MinXp = 4400
                        },
                        new
                        {
                            LevelId = 46,
                            LevelName = "Level 46",
                            MaxXp = 4599,
                            MinXp = 4500
                        },
                        new
                        {
                            LevelId = 47,
                            LevelName = "Level 47",
                            MaxXp = 4699,
                            MinXp = 4600
                        },
                        new
                        {
                            LevelId = 48,
                            LevelName = "Level 48",
                            MaxXp = 4799,
                            MinXp = 4700
                        },
                        new
                        {
                            LevelId = 49,
                            LevelName = "Level 49",
                            MaxXp = 4899,
                            MinXp = 4800
                        },
                        new
                        {
                            LevelId = 50,
                            LevelName = "Level 50",
                            MaxXp = 4999,
                            MinXp = 4900
                        },
                        new
                        {
                            LevelId = 51,
                            LevelName = "Level 51",
                            MaxXp = 5099,
                            MinXp = 5000
                        },
                        new
                        {
                            LevelId = 52,
                            LevelName = "Level 52",
                            MaxXp = 5199,
                            MinXp = 5100
                        },
                        new
                        {
                            LevelId = 53,
                            LevelName = "Level 53",
                            MaxXp = 5299,
                            MinXp = 5200
                        },
                        new
                        {
                            LevelId = 54,
                            LevelName = "Level 54",
                            MaxXp = 5399,
                            MinXp = 5300
                        },
                        new
                        {
                            LevelId = 55,
                            LevelName = "Level 55",
                            MaxXp = 5499,
                            MinXp = 5400
                        },
                        new
                        {
                            LevelId = 56,
                            LevelName = "Level 56",
                            MaxXp = 5599,
                            MinXp = 5500
                        },
                        new
                        {
                            LevelId = 57,
                            LevelName = "Level 57",
                            MaxXp = 5699,
                            MinXp = 5600
                        },
                        new
                        {
                            LevelId = 58,
                            LevelName = "Level 58",
                            MaxXp = 5799,
                            MinXp = 5700
                        },
                        new
                        {
                            LevelId = 59,
                            LevelName = "Level 59",
                            MaxXp = 5899,
                            MinXp = 5800
                        },
                        new
                        {
                            LevelId = 60,
                            LevelName = "Level 60",
                            MaxXp = 5999,
                            MinXp = 5900
                        },
                        new
                        {
                            LevelId = 61,
                            LevelName = "Level 61",
                            MaxXp = 6099,
                            MinXp = 6000
                        },
                        new
                        {
                            LevelId = 62,
                            LevelName = "Level 62",
                            MaxXp = 6199,
                            MinXp = 6100
                        },
                        new
                        {
                            LevelId = 63,
                            LevelName = "Level 63",
                            MaxXp = 6299,
                            MinXp = 6200
                        },
                        new
                        {
                            LevelId = 64,
                            LevelName = "Level 64",
                            MaxXp = 6399,
                            MinXp = 6300
                        },
                        new
                        {
                            LevelId = 65,
                            LevelName = "Level 65",
                            MaxXp = 6499,
                            MinXp = 6400
                        },
                        new
                        {
                            LevelId = 66,
                            LevelName = "Level 66",
                            MaxXp = 6599,
                            MinXp = 6500
                        },
                        new
                        {
                            LevelId = 67,
                            LevelName = "Level 67",
                            MaxXp = 6699,
                            MinXp = 6600
                        },
                        new
                        {
                            LevelId = 68,
                            LevelName = "Level 68",
                            MaxXp = 6799,
                            MinXp = 6700
                        },
                        new
                        {
                            LevelId = 69,
                            LevelName = "Level 69",
                            MaxXp = 6899,
                            MinXp = 6800
                        },
                        new
                        {
                            LevelId = 70,
                            LevelName = "Level 70",
                            MaxXp = 6999,
                            MinXp = 6900
                        },
                        new
                        {
                            LevelId = 71,
                            LevelName = "Level 71",
                            MaxXp = 7099,
                            MinXp = 7000
                        },
                        new
                        {
                            LevelId = 72,
                            LevelName = "Level 72",
                            MaxXp = 7199,
                            MinXp = 7100
                        },
                        new
                        {
                            LevelId = 73,
                            LevelName = "Level 73",
                            MaxXp = 7299,
                            MinXp = 7200
                        },
                        new
                        {
                            LevelId = 74,
                            LevelName = "Level 74",
                            MaxXp = 7399,
                            MinXp = 7300
                        },
                        new
                        {
                            LevelId = 75,
                            LevelName = "Level 75",
                            MaxXp = 7499,
                            MinXp = 7400
                        },
                        new
                        {
                            LevelId = 76,
                            LevelName = "Level 76",
                            MaxXp = 7599,
                            MinXp = 7500
                        },
                        new
                        {
                            LevelId = 77,
                            LevelName = "Level 77",
                            MaxXp = 7699,
                            MinXp = 7600
                        },
                        new
                        {
                            LevelId = 78,
                            LevelName = "Level 78",
                            MaxXp = 7799,
                            MinXp = 7700
                        },
                        new
                        {
                            LevelId = 79,
                            LevelName = "Level 79",
                            MaxXp = 7899,
                            MinXp = 7800
                        },
                        new
                        {
                            LevelId = 80,
                            LevelName = "Level 80",
                            MaxXp = 7999,
                            MinXp = 7900
                        },
                        new
                        {
                            LevelId = 81,
                            LevelName = "Level 81",
                            MaxXp = 8099,
                            MinXp = 8000
                        },
                        new
                        {
                            LevelId = 82,
                            LevelName = "Level 82",
                            MaxXp = 8199,
                            MinXp = 8100
                        },
                        new
                        {
                            LevelId = 83,
                            LevelName = "Level 83",
                            MaxXp = 8299,
                            MinXp = 8200
                        },
                        new
                        {
                            LevelId = 84,
                            LevelName = "Level 84",
                            MaxXp = 8399,
                            MinXp = 8300
                        },
                        new
                        {
                            LevelId = 85,
                            LevelName = "Level 85",
                            MaxXp = 8499,
                            MinXp = 8400
                        },
                        new
                        {
                            LevelId = 86,
                            LevelName = "Level 86",
                            MaxXp = 8599,
                            MinXp = 8500
                        },
                        new
                        {
                            LevelId = 87,
                            LevelName = "Level 87",
                            MaxXp = 8699,
                            MinXp = 8600
                        },
                        new
                        {
                            LevelId = 88,
                            LevelName = "Level 88",
                            MaxXp = 8799,
                            MinXp = 8700
                        },
                        new
                        {
                            LevelId = 89,
                            LevelName = "Level 89",
                            MaxXp = 8899,
                            MinXp = 8800
                        },
                        new
                        {
                            LevelId = 90,
                            LevelName = "Level 90",
                            MaxXp = 8999,
                            MinXp = 8900
                        },
                        new
                        {
                            LevelId = 91,
                            LevelName = "Level 91",
                            MaxXp = 9099,
                            MinXp = 9000
                        },
                        new
                        {
                            LevelId = 92,
                            LevelName = "Level 92",
                            MaxXp = 9199,
                            MinXp = 9100
                        },
                        new
                        {
                            LevelId = 93,
                            LevelName = "Level 93",
                            MaxXp = 9299,
                            MinXp = 9200
                        },
                        new
                        {
                            LevelId = 94,
                            LevelName = "Level 94",
                            MaxXp = 9399,
                            MinXp = 9300
                        },
                        new
                        {
                            LevelId = 95,
                            LevelName = "Level 95",
                            MaxXp = 9499,
                            MinXp = 9400
                        },
                        new
                        {
                            LevelId = 96,
                            LevelName = "Level 96",
                            MaxXp = 9599,
                            MinXp = 9500
                        },
                        new
                        {
                            LevelId = 97,
                            LevelName = "Level 97",
                            MaxXp = 9699,
                            MinXp = 9600
                        },
                        new
                        {
                            LevelId = 98,
                            LevelName = "Level 98",
                            MaxXp = 9799,
                            MinXp = 9700
                        },
                        new
                        {
                            LevelId = 99,
                            LevelName = "Level 99",
                            MaxXp = 9899,
                            MinXp = 9800
                        },
                        new
                        {
                            LevelId = 100,
                            LevelName = "Level 100",
                            MaxXp = 9999,
                            MinXp = 9900
                        });
                });

            modelBuilder.Entity("TaskManager.Modules.Tasks.Models.CompletionFeedback", b =>
                {
                    b.Property<int?>("CompletionFeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("CompletionFeedbackId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DifficultyAverage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("FeedbackFactor")
                        .HasColumnType("decimal(4,2)");

                    b.Property<byte>("PerceivedOutcome")
                        .HasColumnType("tinyint");

                    b.Property<int?>("TaskAssignmentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("XpBase")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("XpFinal")
                        .HasColumnType("int");

                    b.HasKey("CompletionFeedbackId");

                    b.HasIndex("TaskAssignmentId");

                    b.ToTable("CompletionFeedbacks", (string)null);
                });

            modelBuilder.Entity("TaskManager.Modules.Tasks.Models.DifficultyVote", b =>
                {
                    b.Property<int?>("DifficultyVoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("DifficultyVoteId"));

                    b.Property<int?>("TaskAssignmentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<byte>("VoteValue")
                        .HasColumnType("tinyint");

                    b.HasKey("DifficultyVoteId");

                    b.HasIndex("TaskAssignmentId");

                    b.ToTable("DifficultyVotes", (string)null);
                });

            modelBuilder.Entity("TaskManager.Modules.Tasks.Models.TaskAssignment", b =>
                {
                    b.Property<int>("TaskAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskAssignmentId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int?>("TaskId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TaskAssignmentId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskAssignments", (string)null);
                });

            modelBuilder.Entity("TaskManager.Modules.Tasks.Models.UserTask", b =>
                {
                    b.Property<int?>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("TaskId"));

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TaskId");

                    b.ToTable("UserTasks", (string)null);
                });

            modelBuilder.Entity("TaskManager.Modules.Users.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LevelId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalXp")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TaskManager.Modules.Users.Models.LeaderboardEntry", b =>
                {
                    b.Property<int?>("LeaderboardEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("LeaderboardEntryId"));

                    b.Property<DateTime?>("PeriodEnd")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PeriodStart")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rank")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("XpTotal")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("LeaderboardEntryId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaderboardEntries", (string)null);
                });

            modelBuilder.Entity("TaskManager.Modules.Users.Models.UserBadge", b =>
                {
                    b.Property<int?>("UserBadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("UserBadgeId"));

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BadgeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserBadgeId");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBadges", (string)null);
                });

            modelBuilder.Entity("TaskManager.Modules.Users.Models.UserXpHistory", b =>
                {
                    b.Property<int?>("UserXpHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("UserXpHistoryId"));

                    b.Property<int?>("ChangeAmount")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaskAssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserXpHistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserXpHistories", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TaskManager.Modules.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TaskManager.Modules.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManager.Modules.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TaskManager.Modules.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManager.Modules.Tasks.Models.CompletionFeedback", b =>
                {
                    b.HasOne("TaskManager.Modules.Tasks.Models.TaskAssignment", "TaskAssignment")
                        .WithMany("CompletionFeedbacks")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("TaskManager.Modules.Tasks.Models.DifficultyVote", b =>
                {
                    b.HasOne("TaskManager.Modules.Tasks.Models.TaskAssignment", "TaskAssignment")
                        .WithMany("DifficultyVotes")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("TaskManager.Modules.Tasks.Models.TaskAssignment", b =>
                {
                    b.HasOne("TaskManager.Modules.Tasks.Models.UserTask", "Task")
                        .WithMany("Assignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManager.Modules.Users.Models.ApplicationUser", "User")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManager.Modules.Users.Models.ApplicationUser", b =>
                {
                    b.HasOne("TaskManager.Modules.Gamification.Models.Level", "Level")
                        .WithMany("Users")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Level");
                });

            modelBuilder.Entity("TaskManager.Modules.Users.Models.LeaderboardEntry", b =>
                {
                    b.HasOne("TaskManager.Modules.Users.Models.ApplicationUser", "User")
                        .WithMany("LeaderboardEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManager.Modules.Users.Models.UserBadge", b =>
                {
                    b.HasOne("TaskManager.Modules.Gamification.Models.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManager.Modules.Users.Models.ApplicationUser", "User")
                        .WithMany("Badges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManager.Modules.Users.Models.UserXpHistory", b =>
                {
                    b.HasOne("TaskManager.Modules.Users.Models.ApplicationUser", "User")
                        .WithMany("XpHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManager.Modules.Gamification.Models.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("TaskManager.Modules.Gamification.Models.Level", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TaskManager.Modules.Tasks.Models.TaskAssignment", b =>
                {
                    b.Navigation("CompletionFeedbacks");

                    b.Navigation("DifficultyVotes");
                });

            modelBuilder.Entity("TaskManager.Modules.Tasks.Models.UserTask", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("TaskManager.Modules.Users.Models.ApplicationUser", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("LeaderboardEntries");

                    b.Navigation("TaskAssignments");

                    b.Navigation("XpHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
